import type { Project, ProjectImages } from './types';

/** Pictures rendered by tools/shots for each project. */
const shots = (slug: string, name: string): ProjectImages => ({
  hero: { src: `/assets/shots/${slug}-hero.webp`, alt: `${name} on a laptop screen`, width: 1600, height: 1000 },
  tall: { src: `/assets/shots/${slug}-tall.webp`, alt: `${name} on a phone`, width: 1200, height: 1500 },
  detail: { src: `/assets/shots/${slug}-detail.webp`, alt: `A close-up of the ${name} interface`, width: 1600, height: 1000 },
});

export const projects: Project[] = [
  {
    slug: 'ledgerline',
    name: 'Ledgerline',
    category: 'Fintech',
    year: 2026,
    status: 'live',
    statusLabel: 'Live',
    images: shots('ledgerline', 'Ledgerline'),
    caseStudy: {
      overview: 'A real-time treasury dashboard that shows finance teams every incoming and outgoing payment the moment it settles.',
      client: 'Bluefin Payments',
      role: 'Lead frontend engineer',
      stack: 'TypeScript, React, Go, PostgreSQL, Kafka',
      links: [{ label: 'Live site ↗', href: 'https://example.com/' }],
      problem: 'Finance teams reconciled payments from nightly CSV exports. By the time a failed transfer showed up, it was a day old and the customer had already called support.',
      approach: 'We replaced the nightly export with a Kafka event stream. A Go service folds events into per-account balances, and the React client subscribes over Server-Sent Events, so the ledger updates without a refresh.',
      decisions: [
        { title: 'Server-Sent Events over WebSockets.', body: 'The data only flows one way, SSE works through corporate proxies, and the browser reconnects for free.' },
        { title: 'A virtualised table.', body: 'Only visible rows are rendered, so a 50,000-row ledger scrolls at 60 fps.' },
        { title: 'Integer minor units everywhere.', body: 'Amounts are stored and sent as cents from the database to the screen. No floats anywhere.' },
      ],
      code: [
        'const events = new EventSource(`/api/ledger/${accountId}/stream`);',
        '',
        'events.addEventListener("settled", (e) => {',
        '  const tx: Transaction = JSON.parse(e.data);',
        '  ledger.upsert(tx.id, tx);        // O(1) keyed update',
        '  balance.add(tx.amountMinor);     // integer cents, never floats',
        '});',
      ].join('\n'),
      metrics: [
        { value: '140 ms', label: 'p95 time from settlement to screen' },
        { value: '−38%', label: 'fewer “where is my payment” tickets' },
        { value: '50k', label: 'rows scrolled at 60 fps' },
      ],
      outcome: 'Finance now spots failed transfers within seconds instead of the next morning. The same stream later powered customer-facing payment notifications.',
    },
  },
  {
    slug: 'tidepool',
    name: 'Tidepool',
    category: 'Developer tools',
    year: 2025,
    status: 'oss',
    statusLabel: 'Open source',
    images: shots('tidepool', 'Tidepool'),
    caseStudy: {
      overview: 'A fast terminal log viewer that tails, filters and searches gigabytes of structured logs without leaving the keyboard.',
      client: 'Personal open-source project',
      role: 'Author and maintainer',
      stack: 'Rust, Tokio, Ratatui',
      links: [{ label: 'Source on GitHub ↗', href: 'https://github.com/' }],
      problem: 'Reading JSON logs across several services meant chaining jq, less and tail by hand, and those tools struggled on multi-gigabyte files.',
      approach: 'Tidepool memory-maps the file, indexes line offsets in the background and parses JSON only for the lines on screen. Filters compile to a small query language, so level=error and ms>200 runs as fast as a plain text search.',
      decisions: [
        { title: 'Memory-mapped I/O.', body: 'The operating system pages the file in on demand, so opening a 4 GB log doesn’t load 4 GB into memory.' },
        { title: 'Lazy parsing.', body: 'A line is decoded only when it’s visible or matched by a filter.' },
        { title: 'One static binary.', body: 'No runtime dependencies. It installs with a single command on macOS and Linux.' },
      ],
      code: [
        'let mmap = unsafe { Mmap::map(&file)? };',
        'let index = LineIndex::build_in_background(&mmap);',
        '',
        'for line in index.visible(viewport) {',
        '    if query.matches(line) {',
        '        render(line);                // parse on demand',
        '    }',
        '}',
      ].join('\n'),
      metrics: [
        { value: '2.1k', label: 'stars on GitHub' },
        { value: '0.8 s', label: 'to open a 4 GB log' },
        { value: '37', label: 'contributors' },
      ],
      outcome: 'Tidepool is now packaged for Homebrew and several Linux distributions, and two of the teams I’ve worked with use it in their on-call runbooks.',
    },
  },
  {
    slug: 'kiln',
    name: 'Kiln',
    category: 'E-commerce',
    year: 2025,
    status: 'live',
    statusLabel: 'Live',
    images: shots('kiln', 'Kiln'),
    caseStudy: {
      overview: 'A headless storefront for an independent ceramics studio whose collections sell out within hours of release.',
      client: 'Kiln Ceramics Studio',
      role: 'Full-stack engineer',
      stack: 'Astro, TypeScript, Shopify Storefront API, Cloudflare Workers',
      links: [{ label: 'Live site ↗', href: 'https://example.com/' }],
      problem: 'Each release brought thousands of shoppers in the first few minutes. The old theme slowed to a crawl, and it kept selling pieces that were already gone.',
      approach: 'Product pages are static HTML built with Astro. Live stock and cart logic run at the edge on Cloudflare Workers, and an item is reserved for ten minutes as soon as it goes into a cart.',
      decisions: [
        { title: 'Almost no JavaScript.', body: 'Product pages ship only the add-to-cart component. Everything else is HTML and CSS.' },
        { title: 'Reserve stock at add-to-cart.', body: 'Holding items when they enter a cart, rather than at checkout, ended overselling.' },
        { title: 'Sized AVIF images.', body: 'Every image has explicit dimensions, so the layout never jumps while it loads.' },
      ],
      code: [
        'export default {',
        '  async fetch(req: Request, env: Env) {',
        '    const { sku } = await req.json<{ sku: string }>();',
        '    const ok = await env.STOCK.get(sku).reserve({ ttl: 600 });  // 10 min hold',
        '    return Response.json({ reserved: ok }, { status: ok ? 200 : 409 });',
        '  },',
        '};',
      ].join('\n'),
      metrics: [
        { value: '98', label: 'Lighthouse performance score' },
        { value: '+12%', label: 'conversion on release days' },
        { value: '0', label: 'oversold orders since launch' },
      ],
      outcome: 'The studio now releases collections without a support inbox full of refund requests, and hosting costs went down because most pages are static.',
    },
  },
  {
    slug: 'relay',
    name: 'Relay',
    category: 'Collaboration',
    year: 2024,
    status: 'archived',
    statusLabel: 'Archived',
    images: shots('relay', 'Relay'),
    caseStudy: {
      overview: 'A multiplayer whiteboard where distributed teams sketch system diagrams together in real time.',
      client: 'Studio Ferro (internal tool)',
      role: 'Frontend engineer',
      stack: 'TypeScript, Yjs, WebSockets, Canvas 2D',
      links: [{ label: 'Source on GitHub ↗', href: 'https://github.com/' }],
      problem: 'The team drew architecture diagrams in separate tools and pasted screenshots into docs, so every diagram was out of date soon after it was drawn.',
      approach: 'Board state lives in a Yjs CRDT document synced over WebSockets. The canvas redraws only the regions that changed, and edits made offline merge cleanly when a laptop reconnects.',
      decisions: [
        { title: 'CRDTs instead of operational transforms.', body: 'The server only relays messages, which kept it small and easy to run.' },
        { title: 'Canvas 2D instead of SVG.', body: 'Boards with thousands of shapes stay smooth.' },
        { title: 'A separate channel for cursors.', body: 'Presence updates can be dropped without affecting the document.' },
      ],
      code: [
        'const doc = new Y.Doc();',
        'const shapes = doc.getMap<Shape>("shapes");',
        'new WebsocketProvider(RELAY_URL, boardId, doc);',
        '',
        'shapes.observe((e) => renderer.markDirty(e.keysChanged)); // redraw only what changed',
      ].join('\n'),
      metrics: [
        { value: '120', label: 'people on one board in load tests' },
        { value: '16 ms', label: 'frame time with 5,000 shapes' },
        { value: '40+', label: 'boards created per week at peak' },
      ],
      outcome: 'Relay was retired in 2025 when the studio moved to a commercial tool. The source stays public as a reference for CRDT-based editors.',
    },
  },
  {
    slug: 'fieldnote',
    name: 'Fieldnote',
    category: 'AI search',
    year: 2024,
    status: 'live',
    statusLabel: 'Live',
    images: shots('fieldnote', 'Fieldnote'),
    caseStudy: {
      overview: 'Semantic search across an engineering team’s docs, tickets and RFCs, with every answer linked to its source.',
      client: 'Northstar Labs',
      role: 'Backend engineer',
      stack: 'Python, FastAPI, PostgreSQL, pgvector, React',
      links: [{ label: 'Product page ↗', href: 'https://example.com/' }],
      problem: 'Knowledge was spread across four tools. New engineers spent their first weeks asking questions that had already been answered somewhere.',
      approach: 'Documents are split into passages, embedded and stored in PostgreSQL with pgvector. Queries combine vector similarity with keyword ranking, and each result cites the passage it came from.',
      decisions: [
        { title: 'pgvector in the existing database.', body: 'No new vector database to run, back up or secure.' },
        { title: 'Hybrid ranking.', body: 'Error codes and ticket IDs need exact keyword matches that embeddings alone miss.' },
        { title: 'Sources on every answer.', body: 'People can check a result instead of trusting it blindly.' },
      ],
      code: [
        'SELECT id, title,',
        '       0.7 * (1 - (embedding <=> $1))    -- vector similarity',
        '     + 0.3 * ts_rank(tsv, query)          -- keyword match',
        '       AS score',
        'FROM passages, plainto_tsquery($2) AS query',
        'ORDER BY score DESC',
        'LIMIT 8;',
      ].join('\n'),
      metrics: [
        { value: '1.2M', label: 'passages indexed' },
        { value: '310 ms', label: 'median query time' },
        { value: '−45%', label: 'repeat questions in the help channel' },
      ],
      outcome: 'Fieldnote became the default starting point for onboarding, and the team later added it to their incident tooling to surface past postmortems.',
    },
  },
];
